# Generated by Django 5.0.7 on 2024-08-04 23:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendaigreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Digite a descrição aqui: ', verbose_name='Descrição do Evento:')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
            ],
            options={
                'verbose_name': 'Agenda da Igreja',
                'verbose_name_plural': 'Agenda da Igreja',
            },
        ),
        migrations.CreateModel(
            name='Agendapastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Digite a descrição aqui: ', verbose_name='Descrição do Evento:')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
            ],
            options={
                'verbose_name': 'Agenda Pastoral',
                'verbose_name_plural': 'Agenda Pastoral',
            },
        ),
        migrations.CreateModel(
            name='Autoreslivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=80, unique=True, verbose_name='Nome do Autor')),
            ],
            options={
                'verbose_name': 'Autor do Livro',
                'verbose_name_plural': 'Autor do Livro',
            },
        ),
        migrations.CreateModel(
            name='BalanceteMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Total de Entrada')),
                ('total_saidas', models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Total de Pagamentos')),
                ('saldo_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Saldo Mensal')),
            ],
            options={
                'verbose_name': 'Balancete Mensal',
                'verbose_name_plural': 'Balancetes Mensal',
            },
        ),
        migrations.CreateModel(
            name='BancoFinanceiro',
            fields=[
                ('codigo_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nome_banco', models.CharField(max_length=255, verbose_name='Nome do Banco')),
                ('numero_agencia', models.CharField(blank=True, max_length=20, verbose_name='Número da Agência')),
                ('numero_conta', models.CharField(blank=True, max_length=20, verbose_name='Número da Conta')),
                ('cidade_agencia', models.CharField(blank=True, max_length=150, verbose_name='Cidade da Agência')),
                ('tipo_agencia', models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial'), ('posto_avancado', 'Posto Avançado'), ('Outros', 'Outros')], max_length=20, verbose_name='Tipo da Agência')),
                ('titular', models.CharField(blank=True, max_length=255, verbose_name='Titular da Conta')),
                ('data_cadastro', models.DateField(verbose_name='Data de Cadastro')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cadastro de Bancos',
                'verbose_name_plural': 'Cadastro de Bancos',
            },
        ),
        migrations.CreateModel(
            name='Batismoigreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome aqui: ', max_length=200, verbose_name='Nome do Batizando:')),
                ('data_batismo', models.DateField(verbose_name='Data do Batismo')),
            ],
            options={
                'verbose_name': 'Cadastro de Batismo',
                'verbose_name_plural': 'Cadastro de Batismo',
            },
        ),
        migrations.CreateModel(
            name='Biblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.IntegerField()),
                ('versiculo', models.IntegerField()),
                ('nome_livro', models.CharField(max_length=100)),
                ('texto_biblico', models.TextField()),
                ('tipo_testamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bíblia Sagrada',
                'verbose_name_plural': 'Bíblia Sagrada',
            },
        ),
        migrations.CreateModel(
            name='CadastroContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conta', models.CharField(max_length=50, unique=True, verbose_name='Nome da Conta')),
                ('nr_contabil', models.CharField(max_length=50, verbose_name='Número Contábil')),
            ],
            options={
                'verbose_name': 'Cadastro de Contas',
                'verbose_name_plural': 'Cadastro de Contas',
            },
        ),
        migrations.CreateModel(
            name='Cadastroestudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text='Digite a descrição aqui: ', verbose_name='Título do Estudo Bíblico:')),
                ('descricao', models.TextField(help_text='Digite a descrição aqui: ', verbose_name='Descrição do Evento:')),
                ('data_registro', models.DateField(verbose_name='Data do Registro')),
            ],
            options={
                'verbose_name': 'Esboços Bíblicos',
                'verbose_name_plural': 'Esboços Bíblicos',
            },
        ),
        migrations.CreateModel(
            name='CadastroSubcontas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subconta', models.CharField(max_length=50, unique=True, verbose_name='Nome da Subconta')),
                ('nr_subconta', models.CharField(max_length=50, verbose_name='Número Contábil da Subconta')),
            ],
            options={
                'verbose_name': 'Cadastro de Subcontas',
                'verbose_name_plural': 'Cadastro de Subcontas',
            },
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=50, unique=True, verbose_name='Nome do Fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data do Vencimento')),
                ('data_pagto', models.DateField(blank=True, verbose_name='Data do Pagamento')),
                ('descricao', models.TextField(blank=True, help_text='Digite a descrição aqui: ', verbose_name='Descrição da Fatura:')),
            ],
            options={
                'verbose_name': 'Contas a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornec', models.CharField(max_length=10, unique=True, verbose_name='Nome do Fornecedor')),
                ('site', models.CharField(blank=True, max_length=80, verbose_name='Endereço do Site')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='Nome da Cidade')),
                ('telefone', models.CharField(blank=True, max_length=80, verbose_name='Número do Telefone')),
            ],
            options={
                'verbose_name': 'Cadastro de Fornecedor',
                'verbose_name_plural': 'Cadastro de Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_habilidade', models.CharField(max_length=80, unique=True, verbose_name='Nome da Habilidade')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_patr', models.CharField(max_length=80, verbose_name='Nome do Patrimônio')),
                ('codigo_patr', models.CharField(max_length=10, unique=True, verbose_name='Código do Patrimônio')),
                ('cat_patr', models.CharField(blank=True, max_length=80, verbose_name='Categoria do Patrimônio')),
                ('local_patr', models.CharField(blank=True, max_length=80, verbose_name='Local do Patrimônio')),
                ('resp_patr', models.CharField(blank=True, max_length=80, verbose_name='Nome do Responsável')),
            ],
            options={
                'verbose_name': 'Cadastro de Patrimônio',
                'verbose_name_plural': 'Cadastro de Patrimônio',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=80, unique=True, verbose_name='Nome da Profissão')),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
            },
        ),
        migrations.CreateModel(
            name='SaldoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('total_entradas_ano', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Total de Entrada/Ano')),
                ('total_saidas_ano', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Total de Pagamentos/Ano')),
                ('saldo_anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Saldo Anual')),
            ],
            options={
                'verbose_name': 'Saldo Anual',
                'verbose_name_plural': 'Saldo Anual',
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_livro', models.CharField(max_length=80, verbose_name='Título do Livro')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código do Acervo')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='Categoria do Livro')),
                ('qtdes_livros', models.BigIntegerField(verbose_name='Quantidade de Livros: ')),
                ('local', models.CharField(blank=True, max_length=80, verbose_name='Localização do Livro')),
                ('nome_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.autoreslivros', verbose_name='Nome do Autor')),
            ],
            options={
                'verbose_name': 'Acervo da Biblioteca',
                'verbose_name_plural': 'Acervo da Biblioteca',
            },
        ),
        migrations.CreateModel(
            name='EntradaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, help_text='Digite a descrição aqui: ', verbose_name='Descrição da Entrada:')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Entrada')),
                ('data_entrada', models.DateField(verbose_name='Data da Entrada')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.bancofinanceiro', verbose_name='Nome do Banco')),
                ('nome_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cadastrocontas', verbose_name='Contas')),
                ('nome_subconta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cadastrosubcontas', verbose_name='Nome da Subconta')),
            ],
            options={
                'verbose_name': 'Entrada de Valores',
                'verbose_name_plural': 'Entradas de Valores',
            },
        ),
        migrations.CreateModel(
            name='MembroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_membro', models.CharField(max_length=100, verbose_name='Nome do Membro')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_membros/', verbose_name='Foto do Membro')),
                ('data_aniversario', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(blank=True, choices=[('Casado(a)', 'Casado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Não informou', 'Não informou')], default='Não informou', max_length=20, null=True, verbose_name='Estado Civil')),
                ('cargo', models.CharField(blank=True, choices=[('Membro(a)', 'Membro(a)'), ('Pastor(a)', 'Pastor(a)'), ('Pastor(a) Auxiliar', 'Pastor(a) Auxiliar'), ('Líder de grupo caseiro', 'Líder de grupo caseiro'), ('Diácono(nisa)', 'Diácono(nisa)'), ('Presbítero(a)', 'Presbítero(a)'), ('Bispo(a)', 'Bispo(a)'), ('Apostolo(a)', 'Apostolo(a)'), ('Padre', 'Padre'), ('Frei', 'Frei'), ('Sacerdote', 'Sacerdote'), ('Ancião', 'Ancião'), ('Visitante', 'Visitante'), ('Outros', 'Outros')], default='Membro(a)', max_length=100, null=True, verbose_name='Nome do Cargo')),
                ('grupo', models.CharField(blank=True, choices=[('Pastor Senior', 'Pastor Senior'), ('Pastor(a) Auxiliar', 'Pastor(a) Auxiliar'), ('Líder de grupo caseiro', 'Líder de grupo caseiro'), ('Líder de Ministério de Louvor', 'Líder de Ministério de Louvor'), ('Professor de Escola Dominical', 'Professor de Escola Dominical'), ('Líder de Ministério Infantil', 'Líder de Ministério Infantil'), ('Líder de Ministério das Mulheres', 'Líder de Ministério das Mulheres'), ('Líder de Ministério dos Jovens', 'Líder de Ministério dos Jovens'), ('Líder de Ministério das Crianças', 'Líder de Ministério das Crianças'), ('Líder de Organização de Festas', 'Líder de Organização de Festas'), ('Líder de Organização do Presépio', 'Líder de Organização do Presépio'), ('Líder de Organização Festa de Inverno', 'Líder de Organização Festa de Inverno'), ('Líder de Reunião de Oração', 'Líder de Reunião de Oração'), ('Líder de Circulo de Oração', 'Líder de Circulo de Oração'), ('Membro da Diretoria Administrativa', 'Membro da Diretoria Administrativa'), ('Membro do Conselho de Pastores', 'Membro do Conselho de Pastores'), ('Não ocupa cargo de Liderança', 'Não ocupa cargo de Liderança')], default='Não ocupa cargo de Liderança', max_length=100, null=True, verbose_name='Líder de Ministério')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('numero_telefone', models.CharField(blank=True, max_length=15, verbose_name='Número de Telefone')),
                ('cpf', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos', regex='^\\d{11}$')], verbose_name='Número de CPF')),
                ('rg', models.CharField(blank=True, max_length=15, verbose_name='Número do RG')),
                ('cep', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='CEP deve ter 8 dígitos', regex='^\\d{8}$')], verbose_name='CEP do Imóvel:')),
                ('logradouro', models.CharField(blank=True, max_length=100, verbose_name='Nome da Rua:')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento:')),
                ('bairro', models.CharField(blank=True, max_length=50, verbose_name='Bairro:')),
                ('cidade', models.CharField(blank=True, max_length=50, verbose_name='Cidade:')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='Estado:')),
                ('nr_imovel', models.CharField(blank=True, max_length=10, verbose_name='Número do Imóvel')),
                ('observacao', models.TextField(blank=True, max_length=100, verbose_name='Observação: ')),
                ('situacao', models.CharField(blank=True, choices=[('Ativo(a)', 'Ativo(a)'), ('Desligado(a)', 'Desligado(a)')], default='Ativo', max_length=15, null=True, verbose_name='Situação (Ativo ou Desligado)')),
                ('erro_cep', models.CharField(blank=True, max_length=255, verbose_name='Erro ao buscar o CEP')),
                ('nome_habilidade', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.habilidades', verbose_name='Habilidade')),
                ('nome_prof', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.profissao', verbose_name='Profissao')),
            ],
            options={
                'verbose_name': 'Cadastro de Membros',
                'verbose_name_plural': 'Cadastro de Membros',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Empréstimo')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução')),
                ('titulo_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.biblioteca', verbose_name='Título do Livro')),
                ('nome_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.membrofinanceiro', verbose_name='Nome do Membro')),
            ],
            options={
                'verbose_name': 'Empréstimo de Livro',
                'verbose_name_plural': 'Empréstimos de Livros',
                'ordering': ['data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança'), ('Outros', 'Outros')], max_length=20, verbose_name='Tipo de Conta')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_registro', models.DateField(verbose_name='Data do Registro')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.bancofinanceiro', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Depósito Bancário',
                'verbose_name_plural': 'Depósito Bancário',
            },
        ),
        migrations.CreateModel(
            name='SaidaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, help_text='Digite a descrição aqui: ', verbose_name='Descrição do Pagamento:')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('data_saida', models.DateField(verbose_name='Data do Pagamento')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.bancofinanceiro', verbose_name='Nome do Banco')),
                ('nome_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cadastrocontas', verbose_name='Nome da Conta')),
                ('nome_subconta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.cadastrosubcontas', verbose_name='Nome da Subconta')),
            ],
            options={
                'verbose_name': 'Pagamentos Realizados',
                'verbose_name_plural': 'Pagamentos Realizados',
            },
        ),
    ]
